# Generated by Django 3.0.8 on 2020-07-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200728_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Profile'},
        ),
    ]
